##23102C0073

##CHINMAY AMOGH MALVANKAR

##CMPN C




### 1. Creating and merging lists

In [1]:
# Create two lists
list1 <- list(1, 2, 3)
list2 <- list("water", "juice", "lemonade")

# Display the lists
list1
list2

# Merge the lists
list12 <- c(list1, list2)
list12


[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[1]]
[1] "water"

[[2]]
[1] "juice"

[[3]]
[1] "lemonade"

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] "water"

[[5]]
[1] "juice"

[[6]]
[1] "lemonade"

### 2. Converting a list to a vector — `unlist()`

In [2]:
list1 <- list(1, 2, 3)
list2 <- list("water", "juice", "lemonade")

unlist(list1)
unlist(list2)

mode(list1)
mode(unlist(list1))


[1] 1 2 3

[1] "water"    "juice"    "lemonade"

[1] "list"

[1] "numeric"

### 3. Appending to a list — `append()`

In [3]:
list1 <- list(1, 2, 3)
list2 <- list("water", "juice", "lemonade")

append(list1, 100)
append(list2, "coffee")


[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] 100

[[1]]
[1] "water"

[[2]]
[1] "juice"

[[3]]
[1] "lemonade"

[[4]]
[1] "coffee"

### 4. Appending after a particular position

In [4]:
list1 <- list(1, 2, 3)
list2 <- list("water", "juice", "lemonade")

append(list1, 100, after = 2)
append(list2, "coffee", after = 2)


[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 100

[[4]]
[1] 3

[[1]]
[1] "water"

[[2]]
[1] "juice"

[[3]]
[1] "coffee"

[[4]]
[1] "lemonade"

### 5. Removing an element from a list

In [5]:
list1 <- list(1, 2, 3)
list2 <- list("water", "juice", "lemonade")

list1[-2]
list2[-1]


[[1]]
[1] 1

[[2]]
[1] 3

[[1]]
[1] "juice"

[[2]]
[1] "lemonade"

### 6. Extracting elements from a list

In [6]:
list1 <- list(1, 2, 3, 4, 5, 6)
list2 <- list("water", "juice", "lemonade", "tea", "coffee", "milk")

# Extract a range
list1[2:4]

# Extract selected positions
list1[c(1, 3, 5)]

# Same operations for list2
list2[2:4]
list2[c(1, 3, 5)]


[[1]]
[1] 2

[[2]]
[1] 3

[[3]]
[1] 4

[[1]]
[1] 1

[[2]]
[1] 3

[[3]]
[1] 5

[[1]]
[1] "juice"

[[2]]
[1] "lemonade"

[[3]]
[1] "tea"

[[1]]
[1] "water"

[[2]]
[1] "lemonade"

[[3]]
[1] "coffee"

### 7. Heterogeneous / mixed-mode lists

In [7]:
# Lists can contain different types of values
ab <- list(1, 2, 3, "X", "Y", "Z")

# Give the list dimensions
dim(ab) <- c(2, 3)

print(ab)
mode(print(ab))


     [,1] [,2] [,3]
[1,] 1    3    "Y" 
[2,] 2    "X"  "Z" 
     [,1] [,2] [,3]
[1,] 1    3    "Y" 
[2,] 2    "X"  "Z" 


[1] "list"



### 8. Conditional vector indexing

In [8]:
x <- 1:10
x

# Values greater than 5
x[x > 5]

# Even values
x[x %% 2 == 0]

# Odd values
x[x %% 2 == 1]


[1]  1  2  3  4  5  6  7  8  9 10

[1]  6  7  8  9 10

[1]  2  4  6  8 10

[1] 1 3 5 7 9

### 9. Vector with missing observations

In [9]:
x <- 1:10

# Introduce a missing value
x[5] <- NA
x

# Remove missing values
y <- x[!is.na(x)]
y

# Mean with NA and without NA
mean(x)
mean(y)


[1]  1  2  3  4 NA  6  7  8  9 10

[1]  1  2  3  4  6  7  8  9 10

[1] NA

[1] 5.555556

### 9. Negative integer *indexing*

In [31]:
x <- 1:10
x

# Exclude positions 1 through 5
x[-(1:5)]

# Equivalent positive indexing
x[6:10]


[1]  1  2  3  4  5  6  7  8  9 10

[1]  6  7  8  9 10

[1]  6  7  8  9 10

## 10. Named elements / named vectors and lists

In [11]:
z <- list(a1 = 1, a2 = "c", a3 = 1:3)
z

names(z)

# Change the name of the third element
names(z)[3] <- "c2"
z


$a1
[1] 1

$a2
[1] "c"

$a3
[1] 1 2 3

[1] "a1" "a2" "a3"

$a1
[1] 1

$a2
[1] "c"

$c2
[1] 1 2 3

In [12]:
x <- c(water = 1, juice = 2, lemonade = 3)

names(x)

# Access by name
x["juice"]


[1] "water"    "juice"    "lemonade"

juice 
    2

### 11. Empty index

In [13]:
x <- 1:10
x

# Empty index returns the whole object
x[]


[1]  1  2  3  4  5  6  7  8  9 10

[1]  1  2  3  4  5  6  7  8  9 10



### 12. Creating a factor

In [14]:
# Convert categorical values to a factor
factor(c("Red", "Green", "Green", "Blue", "Red"))


[1] Red   Green Green Blue  Red  
Levels: Blue Green Red

### 13. Factor with explicitly specified levels and labels

In [15]:
y <- c(1, 4, 3, 5, 4, 2, 4)

possible.dieface <- c(1, 2, 3, 4, 5, 6)

labels.dieface <- c(
  "one", "two", "three", "four", "five", "six"
)

facy <- factor(
  y,
  levels = possible.dieface,
  labels = labels.dieface
)

facy


[1] one   four  three five  four  two   four 
Levels: one two three four five six

### 14. Factor basics

1.   List item
2.   List item



In [16]:
# A categorical variable can be represented as a factor
x <- factor(c("lemonade", "lemonade", "juice", "lemonade", "water"))

x
levels(x)


[1] lemonade lemonade juice    lemonade water   
Levels: juice lemonade water

[1] "juice"    "lemonade" "water"

### 15. `factor()` usage and help

In [17]:
# General usage:
# factor(x = character(), levels, labels = levels,
#        exclude = NA, ...)

help("factor")



### 16. `as.factor()`

In [18]:
x <- c(3, 4, 5, 6, 1, 2, 3, 3, 4, 4, 5, 6)
x

y <- as.factor(x)
y

levels(y)


[1] 3 4 5 6 1 2 3 3 4 4 5 6

[1] 3 4 5 6 1 2 3 3 4 4 5 6
Levels: 1 2 3 4 5 6

[1] "1" "2" "3" "4" "5" "6"

### 17. Character values converted to a factor

In [19]:
x <- factor(c(
  "lemonade", "lemonade", "juice", "lemonade", "water"
))

x
levels(x)


[1] lemonade lemonade juice    lemonade water   
Levels: juice lemonade water

[1] "juice"    "lemonade" "water"

### 18. `class()`

In [20]:
class(9)
class("9")
class(print)

x <- matrix(nrow = 2, ncol = 2, data = 1:4)
class(x)


[1] "numeric"

[1] "character"

[1] "function"

[1] "matrix" "array"

### 19. `unclass()` with factors

In [21]:
brands <- c("A", "A", "B", "B", "B", "B", "C")
brands

brands_fac <- factor(brands)
brands_fac

# Convert factor codes back to their underlying numbers
unclass(brands_fac)


[1] "A" "A" "B" "B" "B" "B" "C"

[1] A A B B B B C
Levels: A B C

[1] 1 1 2 2 2 2 3
attr(,"levels")
[1] "A" "B" "C"

### 20. Using factor codes to index another vector

In [22]:
colours <- c("blue", "green", "red")
colours

# Use the underlying factor codes as indexes
colours[unclass(brands_fac)]


[1] "blue"  "green" "red"

[1] "blue"  "blue"  "green" "green" "green" "green" "red"

### 21. Inspecting factor codes

In [23]:
x <- factor(c(
  "lemonade", "lemonade", "juice", "lemonade", "water"
))

unclass(x)
levels(x)


[1] 2 2 1 2 3
attr(,"levels")
[1] "juice"    "lemonade" "water"

[1] "juice"    "lemonade" "water"

### 22. Controlling factor level order

In [24]:
x <- factor(
  c("lemonade", "lemonade", "juice", "lemonade", "water"),
  levels = c("water", "juice", "lemonade")
)

x

unclass(x)
levels(x)


[1] lemonade lemonade juice    lemonade water   
Levels: water juice lemonade

[1] 3 3 2 3 1
attr(,"levels")
[1] "water"    "juice"    "lemonade"

[1] "water"    "juice"    "lemonade"

### 23. Ordered factors

In [25]:
income <- ordered(
  c("high", "high", "low", "medium", "medium"),
  levels = c("low", "medium", "high")
)

income
unclass(income)
levels(income)


[1] high   high   low    medium medium
Levels: low < medium < high

[1] 3 3 1 2 2
attr(,"levels")
[1] "low"    "medium" "high"

[1] "low"    "medium" "high"



### 24. `print()`

In [26]:
# Print a number
print(sqrt(2))
print(sqrt(2), digits = 5)
print(sqrt(2), digits = 10)

# Print character values
print("apple")
print(c("apple", "banana"))
print(c("apple", "banana", 6, 10))


[1] 1.414214
[1] 1.4142
[1] 1.414213562
[1] "apple"
[1] "apple"  "banana"
[1] "apple"  "banana" "6"      "10"    


### 25. `format()`

In [27]:
# Basic format
format(0.5)

# Control significant digits and decimal places
print(format(0.5, digits = 10, nsmall = 15))


[1] "0.5"

[1] "0.500000000000000"


## 26. `format()` with width and justification

In [28]:
x <- c("A", "BB", "CCC", "DDDD")

format(x, width = 7, justify = "centre")
format(x, width = 14, justify = "centre")

format(x, width = 7, justify = "left")
format(x, width = 7, justify = "right")
format(x, width = 7, justify = "none")


[1] "   A   " "  BB   " "  CCC  " " DDDD  "

[1] "      A       " "      BB      " "     CCC      " "     DDDD     "

[1] "A      " "BB     " "CCC    " "DDDD   "

[1] "      A" "     BB" "    CCC" "   DDDD"

[1] "A"    "BB"   "CCC"  "DDDD"

### 27. Formatting a **matrix**

In [29]:
x <- matrix(
  nrow = 3,
  ncol = 2,
  data = 1:6,
  byrow = TRUE
)

print(x)


     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6


### 28. Formatting large quantities with `big.mark`

In [30]:
format(1234567, big.mark = ",")
format(12345678, big.mark = ",")
format(123456789, big.mark = ",")

# Using spaces as separators
format(123456789, big.mark = " ")


[1] "1,234,567"

[1] "12,345,678"

[1] "123,456,789"

[1] "123 456 789"